ISSUE_TITLE_MIN_LENGTH = 3
ISSUE_TITLE_MAX_LENGTH = 100
ISSUE_DESCRIPTION_MIN_LENGTH = 5
ISSUE_DESCRIPTION_MAX_LENGTH = 1000
ISSUE_KEY_MIN_LENGTH = 1
ISSUE_KEY_MAX_LENGTH = 50
ISSUE_STORY_POINTS_MIN = 0
ISSUE_STORY_POINTS_MAX = 100
