"""
Project related constants.
"""


PROJECT_NAME_MIN_LENGTH = 3

PROJECT_NAME_MAX_LENGTH = 50

PROJECT_KEY_MIN_LENGTH = 2

PROJECT_KEY_MAX_LENGTH = 10

PROJECT_DESCRIPTION_MIN_LENGTH = 5

PROJECT_DESCRIPTION_MAX_LENGTH = 500