spring.application.name=reimbursement-portal

server.port=8080

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/reimbursement_portal
spring.datasource.username=postgres
spring.datasource.password=garv@782853

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# LOGGING
logging.level.org.springframework=INFO

# COMPANY EMAIL DOMAIN
app.allowed-domain=@company.com